# Generated by Django 5.0.6 on 2024-05-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_title_note_songname'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='albumPic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
