# Generated by Django 5.0.6 on 2024-05-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_note_albumpic_note_artist_note_rating_note_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='rating',
            field=models.IntegerField(default=50),
        ),
    ]
